backend:
  name: git-gateway
  branch: main

media_folder: "videos"
public_folder: "videos"

collections:
  - name: "pages"
    label: "Səhifələr"
    files:
      - name: "home"
        label: "Ana Səhifə"
        file: "content.json"
        fields:
          - {label: "Səhifə Başlığı (SEO)", name: "title", widget: "string"}
          - {label: "Səhifə Təsviri (SEO)", name: "description", widget: "text"}
          - {label: "Hero Başlığı", name: "hero_title", widget: "string"}
          - {label: "Hero Alt Başlığı", name: "hero_subtitle", widget: "text"}
          - {label: "Haqqımızda Başlığı", name: "about_title", widget: "string"}
          - {label: "Haqqımızda Mətni 1", name: "about_text_1", widget: "markdown"}
          - {label: "Haqqımızda Mətni 2", name: "about_text_2", widget: "markdown"}
          - {label: "Video Faylı", name: "about_video", widget: "file"}
          - {label: "Telefon", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Ünvan", name: "address", widget: "string"}
